In [1]:
import numpy as np

In [45]:
weights

array([[0.1691139 ],
       [0.63166948],
       [0.39462844]])

In [81]:
weights * np.array([[1],[2],[3]])

array([[0.1691139 ],
       [1.26333896],
       [1.18388533]])

In [84]:
np.sum(weights * np.array([[1],[2],[3]]))

2.616338185267996

In [86]:
weights.T

array([[0.1691139 , 0.63166948, 0.39462844]])

In [85]:
np.matmul(weights.T, np.array([[1],[2],[3]]))

array([[2.61633819]])

In [82]:
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

In [83]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [56]:
weights[1:]

array([[0.63166948],
       [0.39462844]])

In [69]:
z = np.matmul(features, weights[1:]) + weights[0]

In [70]:
z

array([[0.2796391 ],
       [0.6927459 ],
       [0.73280398]])

In [71]:
np.log(z)

array([[-1.27425545],
       [-0.36709201],
       [-0.31087703]])

In [74]:
np.exp(2)

7.38905609893065

In [68]:
1/(1+np.exp(-0.2796391))

0.5694577422761923

In [79]:
features.shape[0]

3

In [98]:
features[:,1].T * weights

array([[0.00394732, 0.04545297, 0.01816484],
       [0.0147439 , 0.16977465, 0.06784878],
       [0.00921109, 0.10606482, 0.04238777]])

In [102]:
features[:,1].T

array([0.02334117, 0.26877134, 0.10741185])

In [111]:
features[:,1].reshape(features.shape[0],1)

array([[0.02334117],
       [0.26877134],
       [0.10741185]])

In [112]:
weights1 = weights

In [113]:
weights1

array([[0.1691139 ],
       [0.63166948],
       [0.39462844]])

In [114]:
gl = [1,1,-3]

In [115]:
weights1 - 0.01 * np.array(gl).reshape((len(gl), 1))

array([[0.1591139 ],
       [0.62166948],
       [0.42462844]])

In [20]:
'''
dimensions: assume
weights: (m + 1) * 1 where m is the number of features. + 1 because we need the intercept
features: n * m where m is number of features, n is the number of data points
return: n * 1, each value is the prediction 
'''
def sigmoid(weights, features):
    z = np.matmul(features, weights[1:]) + weights[0]
    return 1 / (1 + np.exp(-z))

In [75]:
'''
dimensions: assume
weights: (m + 1) * 1 where m is the number of features. + 1 because we need the intercept
features: n * m where m is number of features, n is the number of data points
actual_ys: n * 1, n is the number of data points
return: one value
'''
def log_likelihood(weights, features, actual_ys):
    z = np.matmul(features, weights[1:]) + weights[0]
    return np.sum(-np.log(1 + np.exp(z))) + np.matmul(actual_ys.T, z)

In [ ]:
'''
dimensions: assume
weights: (m + 1) * 1 where m is the number of features. + 1 because we need the intercept
features: n * m where m is number of features, n is the number of data points
actual_ys: n * 1, n is the number of data points
'''
def learn_weights(actual_ys, features, num_iterations, learning_rate):
    n_feats = features.shape[0]
    # initialize weights
    weights = np.zeros((n_feats + 1, 1))
    
    for i in range(num_iterations):
        dldb = []
        # calculate gradients for all weights
        dldb0 = np.sum(actual_ys - sigmoid(weights, features))
        dldb.append(dldb0)
        for j in range(1, len(weights)):
            dldbj = np.sum((actual_ys - sigmoid(weights, features)) * features[:, j - 1].reshape((features.shape[0], 1)))
            dldb.append(dldbj)
        
        # update weights
        weights = weights - learning_rate * np.array(gl).reshape((len(gl), 1))
        
        if i%1000==0:
            print(log_likelihood(weights,features,actual_ys))
    
    return weights

# Use the following hyperparameters:
# num_iterations = 10000
# learning_rate = 0.00005
# initial weights should be set to 0